config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    resources :articles
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category 
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories=Category.all
  end

  # def new
  #
  # end

  def create
    @category = Category.new(category_params)
     if @category.save
    redirect_to @category
    else
    render plain: params[:category].inspect
    end
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles
  end


  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%=link_to "create new category", new_category_path %>

<%@categories.each do |category|%>
  <%=category.name%>
<%end%>

app/views/categories/new.html.erb
<%=form_for :category , url: categories_path do |f|%>
<div>
<%= f.label :name%> <br>
<%= f.text_field :name%>
</div>

<div >
  <%=f.submit%>
</div>
<%end%>

app/views/categories/show.html.erb
<div><p>
<%=@category.name%>
</p>
</div>
<div>
  <ul>
    <%@articles.each do |article|%>
    <%= article.title%>
    <%=article.description%>
    <%=article.price%>
    <%end%>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CraiglistJunior</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>